### ISSUE TITLE
Include aggregate?

### ISSUE THREAD

**Issue by lunaryorn** [dwijnand/sbt-project-graph#27]
Hi,

thanks for this plugin; really helps to give an overview over complex builds!

Currently it just considers classpath dependencies, ie, `dependsOn`, tho.  Could it also include task dependencies, ie, `aggregate`?  In a complex build setup this also helps to understand what gets build.

**Comment by dwijnand** [comment]
Hey @lunaryorn.

Thank you for the kind words.

Could you provide an example use case, please?

Because I remember thinking about this at the time I was writing sbt-project-graph, and indeed in reviewing the code it uses [[1][]] `ProjectDefinition#uses` [[2][]] which includes `aggregate`.

[1]: https://github.com/dwijnand/sbt-project-graph/blob/v0.2.2/src/main/scala/sbtprojectgraph/Node.scala#L10
[2]: https://github.com/sbt/sbt/blob/v1.1.5/main/src/main/scala/sbt/Project.scala#L87

**Comment by lunaryorn** [comment]
In other words, can we append `[style=dashed]` to arrows that denote `.aggregate`?  That'd be awesome, particularly in large builds :blush:

**Comment by dwijnand** [comment]
Sounds like a great addition!

As you might see from the issue tracker and the git history I've not found the interest in working on this further. So I wouldn't picking this ticket up either.

However if you send a PR I'd be happy to work with you to land it!

**Comment by lunaryorn** [comment]
@dwijnand Sure I'll take a look at some point if I find time.

**Comment by lunaryorn** [comment]
@dwijnand I opened #28.  Hopefully Travis accepts it :blush: 

Would appreciate a review :blush:
